/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakeawayRestaurantsRouteImport } from './routes/takeaway-restaurants'
import { Route as TakeawayPaymentRouteImport } from './routes/takeaway-payment'
import { Route as TakeawayLoginRouteImport } from './routes/takeaway-login'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ModeRouteImport } from './routes/mode'
import { Route as DineInSearchRouteImport } from './routes/dine-in-search'
import { Route as DineInRouteImport } from './routes/dine-in'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TakeawayOrderIdRouteImport } from './routes/takeaway-order.$id'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as RestaurantIdMenuRouteImport } from './routes/restaurant.$id.menu'
import { Route as OrderIdBillRouteImport } from './routes/order.$id.bill'

const TakeawayRestaurantsRoute = TakeawayRestaurantsRouteImport.update({
  id: '/takeaway-restaurants',
  path: '/takeaway-restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeawayPaymentRoute = TakeawayPaymentRouteImport.update({
  id: '/takeaway-payment',
  path: '/takeaway-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeawayLoginRoute = TakeawayLoginRouteImport.update({
  id: '/takeaway-login',
  path: '/takeaway-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeRoute = ModeRouteImport.update({
  id: '/mode',
  path: '/mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DineInSearchRoute = DineInSearchRouteImport.update({
  id: '/dine-in-search',
  path: '/dine-in-search',
  getParentRoute: () => rootRouteImport,
} as any)
const DineInRoute = DineInRouteImport.update({
  id: '/dine-in',
  path: '/dine-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeawayOrderIdRoute = TakeawayOrderIdRouteImport.update({
  id: '/takeaway-order/$id',
  path: '/takeaway-order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdMenuRoute = RestaurantIdMenuRouteImport.update({
  id: '/restaurant/$id/menu',
  path: '/restaurant/$id/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdBillRoute = OrderIdBillRouteImport.update({
  id: '/bill',
  path: '/bill',
  getParentRoute: () => OrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dine-in': typeof DineInRoute
  '/dine-in-search': typeof DineInSearchRoute
  '/mode': typeof ModeRoute
  '/restaurants': typeof RestaurantsRoute
  '/scan': typeof ScanRoute
  '/takeaway-login': typeof TakeawayLoginRoute
  '/takeaway-payment': typeof TakeawayPaymentRoute
  '/takeaway-restaurants': typeof TakeawayRestaurantsRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/takeaway-order/$id': typeof TakeawayOrderIdRoute
  '/order/$id/bill': typeof OrderIdBillRoute
  '/restaurant/$id/menu': typeof RestaurantIdMenuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dine-in': typeof DineInRoute
  '/dine-in-search': typeof DineInSearchRoute
  '/mode': typeof ModeRoute
  '/restaurants': typeof RestaurantsRoute
  '/scan': typeof ScanRoute
  '/takeaway-login': typeof TakeawayLoginRoute
  '/takeaway-payment': typeof TakeawayPaymentRoute
  '/takeaway-restaurants': typeof TakeawayRestaurantsRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/takeaway-order/$id': typeof TakeawayOrderIdRoute
  '/order/$id/bill': typeof OrderIdBillRoute
  '/restaurant/$id/menu': typeof RestaurantIdMenuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dine-in': typeof DineInRoute
  '/dine-in-search': typeof DineInSearchRoute
  '/mode': typeof ModeRoute
  '/restaurants': typeof RestaurantsRoute
  '/scan': typeof ScanRoute
  '/takeaway-login': typeof TakeawayLoginRoute
  '/takeaway-payment': typeof TakeawayPaymentRoute
  '/takeaway-restaurants': typeof TakeawayRestaurantsRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/takeaway-order/$id': typeof TakeawayOrderIdRoute
  '/order/$id/bill': typeof OrderIdBillRoute
  '/restaurant/$id/menu': typeof RestaurantIdMenuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/dine-in'
    | '/dine-in-search'
    | '/mode'
    | '/restaurants'
    | '/scan'
    | '/takeaway-login'
    | '/takeaway-payment'
    | '/takeaway-restaurants'
    | '/order/$id'
    | '/takeaway-order/$id'
    | '/order/$id/bill'
    | '/restaurant/$id/menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/dine-in'
    | '/dine-in-search'
    | '/mode'
    | '/restaurants'
    | '/scan'
    | '/takeaway-login'
    | '/takeaway-payment'
    | '/takeaway-restaurants'
    | '/order/$id'
    | '/takeaway-order/$id'
    | '/order/$id/bill'
    | '/restaurant/$id/menu'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/dine-in'
    | '/dine-in-search'
    | '/mode'
    | '/restaurants'
    | '/scan'
    | '/takeaway-login'
    | '/takeaway-payment'
    | '/takeaway-restaurants'
    | '/order/$id'
    | '/takeaway-order/$id'
    | '/order/$id/bill'
    | '/restaurant/$id/menu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  DineInRoute: typeof DineInRoute
  DineInSearchRoute: typeof DineInSearchRoute
  ModeRoute: typeof ModeRoute
  RestaurantsRoute: typeof RestaurantsRoute
  ScanRoute: typeof ScanRoute
  TakeawayLoginRoute: typeof TakeawayLoginRoute
  TakeawayPaymentRoute: typeof TakeawayPaymentRoute
  TakeawayRestaurantsRoute: typeof TakeawayRestaurantsRoute
  OrderIdRoute: typeof OrderIdRouteWithChildren
  TakeawayOrderIdRoute: typeof TakeawayOrderIdRoute
  RestaurantIdMenuRoute: typeof RestaurantIdMenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/takeaway-restaurants': {
      id: '/takeaway-restaurants'
      path: '/takeaway-restaurants'
      fullPath: '/takeaway-restaurants'
      preLoaderRoute: typeof TakeawayRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takeaway-payment': {
      id: '/takeaway-payment'
      path: '/takeaway-payment'
      fullPath: '/takeaway-payment'
      preLoaderRoute: typeof TakeawayPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takeaway-login': {
      id: '/takeaway-login'
      path: '/takeaway-login'
      fullPath: '/takeaway-login'
      preLoaderRoute: typeof TakeawayLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode': {
      id: '/mode'
      path: '/mode'
      fullPath: '/mode'
      preLoaderRoute: typeof ModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dine-in-search': {
      id: '/dine-in-search'
      path: '/dine-in-search'
      fullPath: '/dine-in-search'
      preLoaderRoute: typeof DineInSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dine-in': {
      id: '/dine-in'
      path: '/dine-in'
      fullPath: '/dine-in'
      preLoaderRoute: typeof DineInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takeaway-order/$id': {
      id: '/takeaway-order/$id'
      path: '/takeaway-order/$id'
      fullPath: '/takeaway-order/$id'
      preLoaderRoute: typeof TakeawayOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id/menu': {
      id: '/restaurant/$id/menu'
      path: '/restaurant/$id/menu'
      fullPath: '/restaurant/$id/menu'
      preLoaderRoute: typeof RestaurantIdMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id/bill': {
      id: '/order/$id/bill'
      path: '/bill'
      fullPath: '/order/$id/bill'
      preLoaderRoute: typeof OrderIdBillRouteImport
      parentRoute: typeof OrderIdRoute
    }
  }
}

interface OrderIdRouteChildren {
  OrderIdBillRoute: typeof OrderIdBillRoute
}

const OrderIdRouteChildren: OrderIdRouteChildren = {
  OrderIdBillRoute: OrderIdBillRoute,
}

const OrderIdRouteWithChildren =
  OrderIdRoute._addFileChildren(OrderIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  DineInRoute: DineInRoute,
  DineInSearchRoute: DineInSearchRoute,
  ModeRoute: ModeRoute,
  RestaurantsRoute: RestaurantsRoute,
  ScanRoute: ScanRoute,
  TakeawayLoginRoute: TakeawayLoginRoute,
  TakeawayPaymentRoute: TakeawayPaymentRoute,
  TakeawayRestaurantsRoute: TakeawayRestaurantsRoute,
  OrderIdRoute: OrderIdRouteWithChildren,
  TakeawayOrderIdRoute: TakeawayOrderIdRoute,
  RestaurantIdMenuRoute: RestaurantIdMenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
