/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ModeRouteImport } from './routes/mode'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as RestaurantIdMenuRouteImport } from './routes/restaurant.$id.menu'
import { Route as OrderIdBillRouteImport } from './routes/order.$id.bill'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeRoute = ModeRouteImport.update({
  id: '/mode',
  path: '/mode',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdMenuRoute = RestaurantIdMenuRouteImport.update({
  id: '/restaurant/$id/menu',
  path: '/restaurant/$id/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdBillRoute = OrderIdBillRouteImport.update({
  id: '/bill',
  path: '/bill',
  getParentRoute: () => OrderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/mode': typeof ModeRoute
  '/restaurants': typeof RestaurantsRoute
  '/scan': typeof ScanRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/order/$id/bill': typeof OrderIdBillRoute
  '/restaurant/$id/menu': typeof RestaurantIdMenuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/mode': typeof ModeRoute
  '/restaurants': typeof RestaurantsRoute
  '/scan': typeof ScanRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/order/$id/bill': typeof OrderIdBillRoute
  '/restaurant/$id/menu': typeof RestaurantIdMenuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/mode': typeof ModeRoute
  '/restaurants': typeof RestaurantsRoute
  '/scan': typeof ScanRoute
  '/order/$id': typeof OrderIdRouteWithChildren
  '/order/$id/bill': typeof OrderIdBillRoute
  '/restaurant/$id/menu': typeof RestaurantIdMenuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/mode'
    | '/restaurants'
    | '/scan'
    | '/order/$id'
    | '/order/$id/bill'
    | '/restaurant/$id/menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/mode'
    | '/restaurants'
    | '/scan'
    | '/order/$id'
    | '/order/$id/bill'
    | '/restaurant/$id/menu'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/mode'
    | '/restaurants'
    | '/scan'
    | '/order/$id'
    | '/order/$id/bill'
    | '/restaurant/$id/menu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ModeRoute: typeof ModeRoute
  RestaurantsRoute: typeof RestaurantsRoute
  ScanRoute: typeof ScanRoute
  OrderIdRoute: typeof OrderIdRouteWithChildren
  RestaurantIdMenuRoute: typeof RestaurantIdMenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode': {
      id: '/mode'
      path: '/mode'
      fullPath: '/mode'
      preLoaderRoute: typeof ModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id/menu': {
      id: '/restaurant/$id/menu'
      path: '/restaurant/$id/menu'
      fullPath: '/restaurant/$id/menu'
      preLoaderRoute: typeof RestaurantIdMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id/bill': {
      id: '/order/$id/bill'
      path: '/bill'
      fullPath: '/order/$id/bill'
      preLoaderRoute: typeof OrderIdBillRouteImport
      parentRoute: typeof OrderIdRoute
    }
  }
}

interface OrderIdRouteChildren {
  OrderIdBillRoute: typeof OrderIdBillRoute
}

const OrderIdRouteChildren: OrderIdRouteChildren = {
  OrderIdBillRoute: OrderIdBillRoute,
}

const OrderIdRouteWithChildren =
  OrderIdRoute._addFileChildren(OrderIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ModeRoute: ModeRoute,
  RestaurantsRoute: RestaurantsRoute,
  ScanRoute: ScanRoute,
  OrderIdRoute: OrderIdRouteWithChildren,
  RestaurantIdMenuRoute: RestaurantIdMenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
